# Generated by Django 5.2.1 on 2025-06-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('mob', models.CharField(max_length=10)),
                ('add', models.TextField()),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
