# Generated by Django 5.2.1 on 2025-06-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='cat_img')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
